#!/usr/bin/env bash
set -euo pipefail

USER_NAME="ugg7"

DOCKER_GPG_URL="https://download.docker.com/linux/debian/gpg"
DOCKER_GPG_KEY="/etc/apt/keyrings/docker.asc"
DOCKER_EXPECTED_FPR="9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

if [[ $EUID -ne 0 ]]; then
  echo "Bitte als root ausführen."
  exit 1
fi

# ---------- Helper ----------
yesno() {
  local prompt="$1"
  local def="${2:-n}"
  local ans

  if [[ "$def" == "y" ]]; then
    read -rp "${prompt} (Y/n): " ans
    ans="${ans,,}"
    [[ -z "$ans" ]] && ans="y"
  else
    read -rp "${prompt} (y/N): " ans
    ans="${ans,,}"
    [[ -z "$ans" ]] && ans="n"
  fi

  [[ "$ans" == "y" || "$ans" == "yes" ]]
}

normalize_fpr() {
  tr -d '[:space:]' | tr '[:lower:]' '[:upper:]'
}

verify_gpg_fingerprint() {
  local key_file="$1"
  local expected="$2"
  local actual=""

  actual="$(gpg --show-keys --with-colons --fingerprint "$key_file" 2>/dev/null \
    | awk -F: '$1 == "fpr" {print $10; exit}' \
    | normalize_fpr)"

  expected="$(printf '%s' "$expected" | normalize_fpr)"

  if [[ -z "$actual" ]]; then
    echo "Fehler: Fingerprint konnte nicht aus ${key_file} gelesen werden."
    return 1
  fi

  if [[ "$actual" != "$expected" ]]; then
    echo "Fehler: GPG-Key-Fingerprint stimmt nicht."
    echo "Erwartet: $expected"
    echo "Gefunden : $actual"
    return 1
  fi

  echo " - Fingerprint OK: $actual"
}

get_current_dns() {
  if command -v resolvectl >/dev/null 2>&1; then
    resolvectl status 2>/dev/null | awk '
      /Current DNS Server:/ {print $0}
      /DNS Servers:/ {print $0}
    ' | sed 's/^[[:space:]]*//'
    return 0
  fi

  if [[ -f /etc/resolv.conf ]]; then
    grep -E '^\s*nameserver\s+' /etc/resolv.conf || true
    return 0
  fi

  echo "Konnte DNS nicht ermitteln."
}

set_dns_systemwide() {
  local dns_list="$1"

  if [[ -d /run/systemd/resolve || -f /lib/systemd/system/systemd-resolved.service || -f /usr/lib/systemd/system/systemd-resolved.service ]]; then
    echo " - Verwende systemd-resolved: /etc/systemd/resolved.conf"
    local conf="/etc/systemd/resolved.conf"

    mkdir -p /etc/systemd
    cp -a "$conf" "${conf}.bak.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true

    if [[ -f "$conf" ]] && grep -qE '^[#[:space:]]*DNS=' "$conf"; then
      sed -i -E "s|^[#[:space:]]*DNS=.*|DNS=${dns_list}|" "$conf"
    else
      if [[ ! -f "$conf" ]] || ! grep -qE '^\[Resolve\]' "$conf"; then
        printf "[Resolve]\n" > "$conf"
      fi
      echo "DNS=${dns_list}" >> "$conf"
    fi

    if command -v systemctl >/dev/null 2>&1; then
      systemctl restart systemd-resolved || true
    fi

    if [[ -e /run/systemd/resolve/stub-resolv.conf ]]; then
      if [[ -f /etc/resolv.conf && ! -L /etc/resolv.conf ]]; then
        cp -a /etc/resolv.conf "/etc/resolv.conf.bak.$(date +%Y%m%d-%H%M%S)" || true
        rm -f /etc/resolv.conf
      fi
      ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
    fi

    echo " - DNS gesetzt via systemd-resolved."
    return 0
  fi

  if [[ -d /etc/dhcp ]]; then
    local dhconf="/etc/dhcp/dhclient.conf"
    cp -a "$dhconf" "${dhconf}.bak.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true

    local dns_csv
    dns_csv="$(echo "$dns_list" | tr ' ' ',')"

    local line="supersede domain-name-servers ${dns_csv};"
    if [[ -f "$dhconf" ]] && grep -qE '^\s*supersede\s+domain-name-servers' "$dhconf"; then
      sed -i -E "s|^\s*supersede\s+domain-name-servers.*;|${line}|" "$dhconf"
    else
      echo "" >> "$dhconf"
      echo "# set by bootstrap script" >> "$dhconf"
      echo "$line" >> "$dhconf"
    fi
    echo " - dhclient.conf angepasst: $line"
  else
    echo " - /etc/dhcp nicht vorhanden, DHCP-supersede nicht gesetzt."
  fi

  {
    echo "# generated by bootstrap script"
    for ns in $dns_list; do
      echo "nameserver $ns"
    done
  } > /etc/resolv.conf

  echo " - /etc/resolv.conf geschrieben (Fallback)."
}

set_hostname_fqdn_systemwide() {
  local new_fqdn="$1"
  local new_host
  new_host="${new_fqdn%%.*}"

  echo " - Setze Hostname: ${new_host}"
  echo "${new_host}" > /etc/hostname

  if command -v hostnamectl >/dev/null 2>&1; then
    hostnamectl set-hostname "${new_fqdn}" || hostnamectl set-hostname "${new_host}" || true
  else
    hostname "${new_host}" || true
  fi

  if grep -qE '^\s*127\.0\.1\.1\s+' /etc/hosts; then
    sed -i -E "s|^\s*127\.0\.1\.1\s+.*|127.0.1.1\t${new_fqdn} ${new_host}|" /etc/hosts
  else
    echo -e "127.0.1.1\t${new_fqdn} ${new_host}" >> /etc/hosts
  fi

  echo " - /etc/hosts aktualisiert."
}

set_locale_systemwide() {
  local locale="$1"

  echo " - Setze Locale: ${locale}"
  apt-get update -y
  apt-get install -y locales

  if grep -qE "^\s*#?\s*${locale}\s+UTF-8\s*$" /etc/locale.gen; then
    sed -i -E "s|^\s*#\s*(${locale}\s+UTF-8\s*)$|\1|" /etc/locale.gen
  else
    echo "${locale} UTF-8" >> /etc/locale.gen
  fi

  locale-gen "${locale}" >/dev/null

  cat > /etc/default/locale <<EOF
LANG=${locale}
LC_ALL=${locale}
EOF

  if command -v localectl >/dev/null 2>&1; then
    localectl set-locale "LANG=${locale}" "LC_ALL=${locale}" || true
  fi
}

get_primary_iface() {
  ip route show default 2>/dev/null | awk '/default/ {print $5; exit}'
}

get_ip_cidr() {
  local ifc="$1"
  ip -o -f inet addr show "$ifc" 2>/dev/null | awk '{print $4; exit}'
}

get_gateway() {
  ip route show default 2>/dev/null | awk '/default/ {print $3; exit}'
}

get_dns_list_compact() {
  if command -v resolvectl >/dev/null 2>&1; then
    resolvectl status 2>/dev/null | awk '/DNS Servers:/ {for (i=3;i<=NF;i++) print $i}' | paste -sd' ' - || true
    return 0
  fi

  grep -E '^\s*nameserver\s+' /etc/resolv.conf 2>/dev/null | awk '{print $2}' | paste -sd' ' - || true
}

cidr_to_netmask() {
  local cidr="$1"
  local p="${cidr#*/}"

  [[ "$p" =~ ^[0-9]+$ ]] || { echo "-"; return 0; }

  local mask=$(( 0xffffffff ^ ((1 << (32 - p)) - 1) ))
  printf "%d.%d.%d.%d" \
    $(( (mask >> 24) & 255 )) \
    $(( (mask >> 16) & 255 )) \
    $(( (mask >> 8) & 255 )) \
    $(( mask & 255 ))
}

get_disk_total() {
  df -h --total 2>/dev/null | awk '/total/ {print $2}' | tail -n1
}

get_ram_total() {
  free -h 2>/dev/null | awk '/Mem:/ {print $2}'
}

USER_CREATED_STATUS="unbekannt"

# ---------- Start ----------
echo "[0/9] Sprache/Locale (Standard: Deutsch)"
DEFAULT_LOCALE="de_DE.UTF-8"
read -rp "Sprache/Locale [${DEFAULT_LOCALE}] (z.B. de_DE.UTF-8 oder en_US.UTF-8): " LOCALE_CHOICE
LOCALE_CHOICE="$(echo "${LOCALE_CHOICE:-$DEFAULT_LOCALE}" | xargs)"

if [[ -n "${LOCALE_CHOICE}" ]]; then
  set_locale_systemwide "${LOCALE_CHOICE}"
fi

echo
echo "[1/9] Hostname/FQDN (passt zur DNS-Abfrage)"
CURRENT_FQDN="$(hostname -f 2>/dev/null || true)"
CURRENT_HOST="$(hostname 2>/dev/null || true)"
SUGGEST_FQDN="${CURRENT_FQDN:-$CURRENT_HOST}"

echo "Aktuell: Hostname='${CURRENT_HOST}', FQDN='${CURRENT_FQDN:-unbekannt}'"

if yesno "Soll Hostname/FQDN geändert werden?" "n"; then
  read -rp "Neuer FQDN [${SUGGEST_FQDN}]: " NEW_FQDN
  NEW_FQDN="$(echo "${NEW_FQDN:-$SUGGEST_FQDN}" | xargs)"
  if [[ -n "${NEW_FQDN}" ]]; then
    set_hostname_fqdn_systemwide "${NEW_FQDN}"
  fi
else
  echo " - Hostname/FQDN bleibt unverändert."
fi

echo
echo "[2/9] SSH-Key: erzeugen oder bereits vorhanden?"
echo " - Wenn du schon einen Public-Key hochgeladen hast: später ~/.ssh/authorized_keys prüfen."

GENKEY=false
if yesno "Soll für ${USER_NAME} ein SSH-Schlüssel erzeugt werden?" "n"; then
  GENKEY=true
fi

echo
echo "[3/9] System aktualisieren"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

echo
echo "[4/9] Basistools installieren: mc, vim, vnstat, tmux"
apt-get install -y mc vim vnstat tmux

echo
echo "[5/9] Globale vim Einstellungen (für alle Nutzer)"
VIMRC_LOCAL="/etc/vim/vimrc.local"
touch "${VIMRC_LOCAL}"
grep -qE '^\s*syntax\s+on\s*$' "${VIMRC_LOCAL}" || echo "syntax on" >> "${VIMRC_LOCAL}"
grep -qE '^\s*set\s+mouse-=a\s*$' "${VIMRC_LOCAL}" || echo "set mouse-=a" >> "${VIMRC_LOCAL}"
echo " - OK: ${VIMRC_LOCAL}"

echo
echo "[6/9] Globales bash alias für alle Nutzer: ll='ls -lha'"
ALIAS_FILE="/etc/profile.d/aliases.sh"
cat > "${ALIAS_FILE}" <<'EOF'
# Global aliases for all users
alias ll='ls -lha'
EOF
chmod 0644 "${ALIAS_FILE}"
echo " - OK: ${ALIAS_FILE}"

echo
echo "[7/9] Systemweite tmux Konfiguration (/etc/tmux.conf)"
TMUX_CONF="/etc/tmux.conf"
cat > "${TMUX_CONF}" <<'EOF'
# System-wide tmux config
set -g status on
set -g status-interval 5
set -g status-left-length 60
set -g status-left " #H | #([ -n \"$LOGNAME\" ] && echo \"$LOGNAME\" || whoami) "
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " *#I:#W* "
set -g status-right-length 80
set -g status-right " %Y-%m-%d %H:%M "
EOF
chmod 0644 "${TMUX_CONF}"
echo " - OK: ${TMUX_CONF}"

echo
echo "[DNS] DNS-Konfiguration (Standard: DHCP beibehalten)"
echo "Aktuell genutzte DNS-Info:"
get_current_dns
echo

if yesno "DNS ändern? (Standard: DHCP beibehalten)" "n"; then
  read -rp "Neue DNS Server (Leerzeichen-getrennt, z.B. '1.1.1.1 8.8.8.8'): " NEWDNS
  NEWDNS="$(echo "${NEWDNS:-}" | xargs)"

  if [[ -z "$NEWDNS" ]]; then
    echo " - Keine DNS Server angegeben, DHCP bleibt."
  else
    set_dns_systemwide "$NEWDNS"
    echo
    echo "DNS ist nun konfiguriert. Aktueller Status:"
    get_current_dns
  fi
else
  echo " - DHCP bleibt aktiv (keine DNS-Änderung)."
fi

# ---------- SSH / User Safety ----------
echo
echo "[8/9] SSH-Schlüssel Routine für ${USER_NAME}"

if id "${USER_NAME}" >/dev/null 2>&1; then
  USER_CREATED_STATUS="vorhanden"
else
  USER_CREATED_STATUS="NICHT vorhanden"
  echo "⚠ Benutzer ${USER_NAME} existiert nicht."
  if yesno "Soll der Benutzer ${USER_NAME} jetzt angelegt werden?" "n"; then
    useradd -m -s /bin/bash "${USER_NAME}"
    echo "Setze jetzt ein Passwort für ${USER_NAME}:"
    passwd "${USER_NAME}"
    USER_CREATED_STATUS="neu angelegt"
    echo " - Benutzer ${USER_NAME} wurde angelegt."
  else
    echo " - SSH-Key Einrichtung wird übersprungen."
  fi
fi

if id "${USER_NAME}" >/dev/null 2>&1; then
  USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6)"
  SSH_DIR="${USER_HOME}/.ssh"
  KEY_PATH="${SSH_DIR}/id_ed25519"
  AUTH_KEYS="${SSH_DIR}/authorized_keys"

  mkdir -p "${SSH_DIR}"
  chown -R "${USER_NAME}:${USER_NAME}" "${SSH_DIR}"
  chmod 700 "${SSH_DIR}"

  if [[ "${GENKEY}" == "true" ]]; then
    if ! command -v ssh-keygen >/dev/null 2>&1; then
      apt-get install -y openssh-client
    fi

    if [[ -f "${KEY_PATH}" ]]; then
      echo " - Key existiert bereits: ${KEY_PATH}"
    else
      echo
      echo "Sicherheitshinweis:"
      echo "Ein privater SSH-Key ohne Passphrase ist bei Diebstahl sofort nutzbar."
      if yesno "Soll der Key trotzdem OHNE Passphrase erzeugt werden?" "n"; then
        echo " - Erzeuge ed25519 Key für ${USER_NAME} ohne Passphrase..."
        sudo -u "${USER_NAME}" ssh-keygen -t ed25519 -f "${KEY_PATH}" -N "" -C "${USER_NAME}@$(hostname)"
      else
        echo " - Erzeuge ed25519 Key für ${USER_NAME}; Passphrase wird interaktiv abgefragt..."
        sudo -u "${USER_NAME}" ssh-keygen -t ed25519 -f "${KEY_PATH}" -C "${USER_NAME}@$(hostname)"
      fi

      chmod 600 "${KEY_PATH}"
      chmod 644 "${KEY_PATH}.pub"
      chown "${USER_NAME}:${USER_NAME}" "${KEY_PATH}" "${KEY_PATH}.pub"
    fi

    echo
    echo "Privater Schlüssel:"
    echo "  ${KEY_PATH}"
    echo
    echo "Public-Key anzeigen:"
    echo "  cat ${KEY_PATH}.pub"
    echo
    echo "Reminder: Public-Key auf Ziel/Server in ~/.ssh/authorized_keys eintragen."
  else
    echo " - Kein Key erzeugt (ausgewählt)."
    echo "Wenn du bereits einen Key hochgeladen hast, stelle sicher:"
    echo " - ${AUTH_KEYS} existiert und gehört ${USER_NAME}:${USER_NAME}"
    echo " - Rechte: ~/.ssh = 700, authorized_keys = 600"
  fi

  if [[ -f "${AUTH_KEYS}" ]]; then
    chown "${USER_NAME}:${USER_NAME}" "${AUTH_KEYS}"
    chmod 600 "${AUTH_KEYS}"
  fi

  echo
  echo "Teste JETZT bitte den SSH-Login (falls SSH genutzt wird)."
  read -rp "ENTER drücken, sobald du getestet hast (oder STRG+C zum Abbrechen) ... " _

  if yesno "Soll ich sshd_config für Key-only Login anpassen und ssh/sshd neu laden?" "n"; then
    if [[ ! -s "${AUTH_KEYS}" ]]; then
      echo
      echo "ABBRUCH: ${AUTH_KEYS} existiert nicht oder ist leer."
      echo "PasswordAuthentication wird NICHT deaktiviert, damit du dich nicht aussperrst."
      echo "Lege zuerst einen funktionierenden Public-Key in ${AUTH_KEYS} ab."
    else
      if ! dpkg -s openssh-server >/dev/null 2>&1; then
        echo "openssh-server ist nicht installiert. Installiere..."
        apt-get install -y openssh-server
      fi

      SSHD_CONFIG="/etc/ssh/sshd_config"
      cp -a "${SSHD_CONFIG}" "${SSHD_CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"

      set_sshd_option() {
        local key="$1"
        local value="$2"

        if grep -qE "^[#[:space:]]*${key}[[:space:]]+" "${SSHD_CONFIG}"; then
          sed -i -E "s|^[#[:space:]]*${key}[[:space:]]+.*|${key} ${value}|g" "${SSHD_CONFIG}"
        else
          echo "${key} ${value}" >> "${SSHD_CONFIG}"
        fi
      }

      set_sshd_option "PubkeyAuthentication" "yes"
      set_sshd_option "PasswordAuthentication" "no"
      set_sshd_option "ChallengeResponseAuthentication" "no"
      set_sshd_option "KbdInteractiveAuthentication" "no"

      if sshd -t; then
        if command -v systemctl >/dev/null 2>&1; then
          systemctl reload ssh || systemctl reload sshd || systemctl restart ssh || systemctl restart sshd
        else
          service ssh reload || service ssh restart || true
        fi
        echo " - SSH/sshd neu geladen."
      else
        echo "Fehler: sshd_config ist ungültig. Backup liegt neben ${SSHD_CONFIG}."
        exit 1
      fi
    fi
  else
    echo "OK, keine automatische SSH-Härtung vorgenommen."
  fi
else
  echo " - Benutzer ${USER_NAME} existiert nicht. SSH-Abschnitt vollständig übersprungen."
fi

echo
echo "[9/9] Optional: Docker (offizielles Docker Repository) installieren?"

if yesno "Soll Docker installiert werden?" "n"; then
  echo " - Entferne ggf. konfliktierende/alte Docker-Pakete (falls vorhanden)..."
  apt-get remove -y docker.io docker-doc docker-compose podman-docker containerd runc 2>/dev/null || true

  echo " - Installiere Voraussetzungen"
  apt-get update -y
  apt-get install -y ca-certificates curl gpg

  install -m 0755 -d /etc/apt/keyrings

  echo " - Lade Docker GPG-Key"
  curl -fsSL --proto '=https' --tlsv1.2 "${DOCKER_GPG_URL}" -o "${DOCKER_GPG_KEY}"
  chmod a+r "${DOCKER_GPG_KEY}"

  echo " - Prüfe Docker GPG-Key-Fingerprint"
  verify_gpg_fingerprint "${DOCKER_GPG_KEY}" "${DOCKER_EXPECTED_FPR}"

  . /etc/os-release
  ARCH="$(dpkg --print-architecture)"
  CODENAME="${VERSION_CODENAME:-trixie}"

  cat > /etc/apt/sources.list.d/docker.list <<EOF
deb [arch=${ARCH} signed-by=${DOCKER_GPG_KEY}] https://download.docker.com/linux/debian ${CODENAME} stable
EOF

  echo " - Installiere Docker Engine"
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  if id "${USER_NAME}" >/dev/null 2>&1; then
    echo
    echo "Sicherheitshinweis:"
    echo "Die docker-Gruppe ist praktisch root-gleichwertig."
    echo "Mitglieder können Container mit Host-Mounts starten und dadurch Root-Rechte auf dem Host erlangen."
    if yesno "Soll ${USER_NAME} trotzdem zur docker-Gruppe hinzugefügt werden?" "n"; then
      usermod -aG docker "${USER_NAME}" 2>/dev/null || true
      echo " - ${USER_NAME} zur docker-Gruppe hinzugefügt (wirksam nach neuem Login)."
    else
      echo " - ${USER_NAME} wurde NICHT zur docker-Gruppe hinzugefügt."
    fi
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl enable --now docker || true
  else
    service docker start || true
  fi

  docker version || true
else
  echo " - Docker Installation übersprungen."
fi

# ---------- Status-Ausgabe ----------
echo
echo "==================== STATUS ===================="
FINAL_HOST="$(hostname 2>/dev/null || true)"
FINAL_FQDN="$(hostname -f 2>/dev/null || true)"
IFACE="$(get_primary_iface)"
IP_CIDR="-"
NETMASK="-"
GATEWAY="$(get_gateway || true)"
DNS_LIST="$(get_dns_list_compact || true)"

if [[ -n "${IFACE}" ]]; then
  IP_CIDR="$(get_ip_cidr "${IFACE}" || true)"
  if [[ -n "${IP_CIDR}" && "${IP_CIDR}" != "-" ]]; then
    NETMASK="$(cidr_to_netmask "${IP_CIDR}")"
  fi
fi

LANGUAGE="$(grep -E '^LANG=' /etc/default/locale 2>/dev/null | head -n1 | cut -d= -f2- || true)"
DISK_TOTAL="$(get_disk_total || true)"
RAM_TOTAL="$(get_ram_total || true)"

echo "Hostname / FQDN : ${FINAL_HOST} / ${FINAL_FQDN}"
echo "Netzwerk        : Interface=${IFACE:-unbekannt}"
echo "IP / Netzmaske  : ${IP_CIDR:--} / ${NETMASK:--}"
echo "Gateway         : ${GATEWAY:--}"
echo "DNS             : ${DNS_LIST:--}"
echo "Sprache/Locale  : ${LANGUAGE:--}"
echo "HDD Gesamt      : ${DISK_TOTAL:--}"
echo "RAM Gesamt      : ${RAM_TOTAL:--}"
echo "Benutzer ugg7   : ${USER_CREATED_STATUS}"
echo "================================================"

echo
echo "Fertig."

    return 0
  fi
  if [[ -f /etc/resolv.conf ]]; then
    grep -E '^\s*nameserver\s+' /etc/resolv.conf || true
    return 0
  fi
  echo "Konnte DNS nicht ermitteln."
}

set_dns_systemwide() {
  local dns_list="$1"   # space-separated, e.g. "1.1.1.1 8.8.8.8"

  # systemd-resolved vorhanden?
  if [[ -d /run/systemd/resolve || -f /lib/systemd/system/systemd-resolved.service || -f /usr/lib/systemd/system/systemd-resolved.service ]]; then
    echo " - Verwende systemd-resolved: /etc/systemd/resolved.conf"
    local conf="/etc/systemd/resolved.conf"
    mkdir -p /etc/systemd
    cp -a "$conf" "${conf}.bak.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true

    if [[ -f "$conf" ]] && grep -qE '^[#[:space:]]*DNS=' "$conf"; then
      sed -i -E "s|^[#[:space:]]*DNS=.*|DNS=${dns_list}|" "$conf"
    else
      if [[ ! -f "$conf" ]] || ! grep -qE '^\[Resolve\]' "$conf"; then
        printf "[Resolve]\n" > "$conf"
      fi
      echo "DNS=${dns_list}" >> "$conf"
    fi

    if command -v systemctl >/dev/null 2>&1; then
      systemctl restart systemd-resolved || true
    fi

    if [[ -e /run/systemd/resolve/stub-resolv.conf ]]; then
      if [[ -f /etc/resolv.conf && ! -L /etc/resolv.conf ]]; then
        cp -a /etc/resolv.conf "/etc/resolv.conf.bak.$(date +%Y%m%d-%H%M%S)" || true
        rm -f /etc/resolv.conf
      fi
      ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
    fi

    echo " - DNS gesetzt via systemd-resolved."
    return 0
  fi

  # Fallback: dhclient.conf supersede + resolv.conf schreiben
  if [[ -d /etc/dhcp ]]; then
    local dhconf="/etc/dhcp/dhclient.conf"
    cp -a "$dhconf" "${dhconf}.bak.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true

    local dns_csv
    dns_csv="$(echo "$dns_list" | tr ' ' ',')"
    local line="supersede domain-name-servers ${dns_csv};"

    if [[ -f "$dhconf" ]] && grep -qE '^\s*supersede\s+domain-name-servers' "$dhconf"; then
      sed -i -E "s|^\s*supersede\s+domain-name-servers.*;|${line}|" "$dhconf"
    else
      echo "" >> "$dhconf"
      echo "# set by bootstrap script" >> "$dhconf"
      echo "$line" >> "$dhconf"
    fi
    echo " - dhclient.conf angepasst: $line"
  else
    echo " - /etc/dhcp nicht vorhanden, DHCP-supersede nicht gesetzt."
  fi

  {
    echo "# generated by bootstrap script"
    for ns in $dns_list; do
      echo "nameserver $ns"
    done
  } > /etc/resolv.conf

  echo " - /etc/resolv.conf geschrieben (Fallback)."
}

set_hostname_fqdn_systemwide() {
  local new_fqdn="$1"
  local new_host
  new_host="${new_fqdn%%.*}"

  echo " - Setze Hostname: ${new_host}"
  echo "${new_host}" > /etc/hostname

  if command -v hostnamectl >/dev/null 2>&1; then
    hostnamectl set-hostname "${new_fqdn}" || hostnamectl set-hostname "${new_host}" || true
  else
    hostname "${new_host}" || true
  fi

  # /etc/hosts anpassen: 127.0.1.1 fqdn hostname
  if grep -qE '^\s*127\.0\.1\.1\s+' /etc/hosts; then
    sed -i -E "s|^\s*127\.0\.1\.1\s+.*|127.0.1.1\t${new_fqdn} ${new_host}|" /etc/hosts
  else
    echo -e "127.0.1.1\t${new_fqdn} ${new_host}" >> /etc/hosts
  fi

  echo " - /etc/hosts aktualisiert."
}

set_locale_systemwide() {
  local locale="$1"   # e.g. de_DE.UTF-8
  echo " - Setze Locale: ${locale}"

  apt-get update -y
  apt-get install -y locales

  if grep -qE "^\s*#?\s*${locale}\s+UTF-8\s*$" /etc/locale.gen; then
    sed -i -E "s|^\s*#\s*(${locale}\s+UTF-8\s*)$|\1|" /etc/locale.gen
  else
    echo "${locale} UTF-8" >> /etc/locale.gen
  fi

  locale-gen "${locale}" >/dev/null

  cat > /etc/default/locale <<EOF
LANG=${locale}
LC_ALL=${locale}
EOF

  if command -v localectl >/dev/null 2>&1; then
    localectl set-locale "LANG=${locale}" "LC_ALL=${locale}" || true
  fi
}

get_primary_iface() {
  ip route show default 2>/dev/null | awk '/default/ {print $5; exit}'
}

get_ip_cidr() {
  local ifc="$1"
  ip -o -f inet addr show "$ifc" 2>/dev/null | awk '{print $4; exit}'
}

get_gateway() {
  ip route show default 2>/dev/null | awk '/default/ {print $3; exit}'
}

get_dns_list_compact() {
  if command -v resolvectl >/dev/null 2>&1; then
    resolvectl status 2>/dev/null | awk '/DNS Servers:/ {for (i=3;i<=NF;i++) print $i}' | paste -sd' ' - || true
    return 0
  fi
  grep -E '^\s*nameserver\s+' /etc/resolv.conf 2>/dev/null | awk '{print $2}' | paste -sd' ' - || true
}

cidr_to_netmask() {
  local cidr="$1"
  local p="${cidr#*/}"
  [[ "$p" =~ ^[0-9]+$ ]] || { echo "-"; return 0; }
  local mask=$(( 0xffffffff ^ ((1 << (32 - p)) - 1) ))
  printf "%d.%d.%d.%d" \
    $(( (mask >> 24) & 255 )) \
    $(( (mask >> 16) & 255 )) \
    $(( (mask >> 8) & 255 )) \
    $(( mask & 255 ))
}

get_disk_total() {
  df -h --total 2>/dev/null | awk '/total/ {print $2}' | tail -n1
}

get_ram_total() {
  free -h 2>/dev/null | awk '/Mem:/ {print $2}'
}

# Track whether user existed / created
USER_CREATED_STATUS="unbekannt"

# ---------- Start ----------
echo "[0/9] Sprache/Locale (Standard: Deutsch)"
DEFAULT_LOCALE="de_DE.UTF-8"
read -rp "Sprache/Locale [${DEFAULT_LOCALE}] (z.B. de_DE.UTF-8 oder en_US.UTF-8): " LOCALE_CHOICE
LOCALE_CHOICE="$(echo "${LOCALE_CHOICE:-$DEFAULT_LOCALE}" | xargs)"
if [[ -n "${LOCALE_CHOICE}" ]]; then
  set_locale_systemwide "${LOCALE_CHOICE}"
fi

echo
echo "[1/9] Hostname/FQDN (passt zur DNS-Abfrage)"
CURRENT_FQDN="$(hostname -f 2>/dev/null || true)"
CURRENT_HOST="$(hostname 2>/dev/null || true)"
SUGGEST_FQDN="${CURRENT_FQDN:-$CURRENT_HOST}"

echo "Aktuell: Hostname='${CURRENT_HOST}', FQDN='${CURRENT_FQDN:-unbekannt}'"
if yesno "Soll Hostname/FQDN geändert werden?" "n"; then
  read -rp "Neuer FQDN [${SUGGEST_FQDN}]: " NEW_FQDN
  NEW_FQDN="$(echo "${NEW_FQDN:-$SUGGEST_FQDN}" | xargs)"
  if [[ -n "${NEW_FQDN}" ]]; then
    set_hostname_fqdn_systemwide "${NEW_FQDN}"
  fi
else
  echo " - Hostname/FQDN bleibt unverändert."
fi

echo
echo "[2/9] SSH-Key: erzeugen oder bereits vorhanden?"
echo " - Wenn du schon einen Public-Key hochgeladen hast: später ~/.ssh/authorized_keys prüfen."
GENKEY=false
if yesno "Soll für ${USER_NAME} ein SSH-Schlüssel erzeugt werden?" "n"; then
  GENKEY=true
fi

echo
echo "[3/9] System aktualisieren"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

echo
echo "[4/9] Basistools installieren: mc, vim, vnstat, tmux"
apt-get install -y mc vim vnstat tmux

echo
echo "[5/9] Globale vim Einstellungen (für alle Nutzer)"
VIMRC_LOCAL="/etc/vim/vimrc.local"
touch "${VIMRC_LOCAL}"
grep -qE '^\s*syntax\s+on\s*$' "${VIMRC_LOCAL}" || echo "syntax on" >> "${VIMRC_LOCAL}"
grep -qE '^\s*set\s+mouse-=a\s*$' "${VIMRC_LOCAL}" || echo "set mouse-=a" >> "${VIMRC_LOCAL}"
echo " - OK: ${VIMRC_LOCAL}"

echo
echo "[6/9] Globales bash alias für alle Nutzer: ll='ls -lha'"
ALIAS_FILE="/etc/profile.d/aliases.sh"
cat > "${ALIAS_FILE}" <<'EOF'
# Global aliases for all users
alias ll='ls -lha'
EOF
chmod 0644 "${ALIAS_FILE}"
echo " - OK: ${ALIAS_FILE}"

echo
echo "[7/9] Systemweite tmux Konfiguration (/etc/tmux.conf)"
TMUX_CONF="/etc/tmux.conf"
cat > "${TMUX_CONF}" <<'EOF'
# System-wide tmux config

set -g status on
set -g status-interval 5

set -g status-left-length 60
set -g status-left " #H | #([ -n \"$LOGNAME\" ] && echo \"$LOGNAME\" || whoami) "

setw -g window-status-format " #I:#W "
setw -g window-status-current-format " *#I:#W* "

set -g status-right-length 80
set -g status-right " %Y-%m-%d %H:%M "
EOF
chmod 0644 "${TMUX_CONF}"
echo " - OK: ${TMUX_CONF}"

echo
echo "[DNS] DNS-Konfiguration (Standard: DHCP beibehalten)"
echo "Aktuell genutzte DNS-Info:"
get_current_dns
echo

if yesno "DNS ändern? (Standard: DHCP beibehalten)" "n"; then
  read -rp "Neue DNS Server (Leerzeichen-getrennt, z.B. '1.1.1.1 8.8.8.8'): " NEWDNS
  NEWDNS="$(echo "${NEWDNS:-}" | xargs)"
  if [[ -z "$NEWDNS" ]]; then
    echo " - Keine DNS Server angegeben, DHCP bleibt."
  else
    set_dns_systemwide "$NEWDNS"
    echo
    echo "DNS ist nun konfiguriert. Aktueller Status:"
    get_current_dns
  fi
else
  echo " - DHCP bleibt aktiv (keine DNS-Änderung)."
fi

# ---------- SSH / User Safety ----------
echo
echo "[8/9] SSH-Schlüssel Routine für ${USER_NAME}"

if id "${USER_NAME}" >/dev/null 2>&1; then
  USER_CREATED_STATUS="vorhanden"
else
  USER_CREATED_STATUS="NICHT vorhanden"
  echo "⚠ Benutzer ${USER_NAME} existiert nicht."
  if yesno "Soll der Benutzer ${USER_NAME} jetzt angelegt werden?" "n"; then
    useradd -m -s /bin/bash "${USER_NAME}"
    echo "Setze jetzt ein Passwort für ${USER_NAME}:"
    passwd "${USER_NAME}"
    USER_CREATED_STATUS="neu angelegt"
    echo " - Benutzer ${USER_NAME} wurde angelegt."
  else
    echo " - SSH-Key Einrichtung wird übersprungen."
  fi
fi

if id "${USER_NAME}" >/dev/null 2>&1; then
  USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6)"
  SSH_DIR="${USER_HOME}/.ssh"
  KEY_PATH="${SSH_DIR}/id_ed25519"

  mkdir -p "${SSH_DIR}"
  chown -R "${USER_NAME}:${USER_NAME}" "${SSH_DIR}"
  chmod 700 "${SSH_DIR}"

  if [[ "${GENKEY}" == "true" ]]; then
    if ! command -v ssh-keygen >/dev/null 2>&1; then
      apt-get install -y openssh-client
    fi

    if [[ -f "${KEY_PATH}" ]]; then
      echo " - Key existiert bereits: ${KEY_PATH}"
    else
      echo " - Erzeuge ed25519 Key für ${USER_NAME} (ohne Passphrase)..."
      sudo -u "${USER_NAME}" ssh-keygen -t ed25519 -f "${KEY_PATH}" -N "" -C "${USER_NAME}@$(hostname)"
      chmod 600 "${KEY_PATH}"
      chmod 644 "${KEY_PATH}.pub"
      chown "${USER_NAME}:${USER_NAME}" "${KEY_PATH}" "${KEY_PATH}.pub"
    fi

    echo
    echo "Privater Schlüssel:"
    echo "  ${KEY_PATH}"
    echo
    echo "Reminder: Public-Key auf Ziel/Server in ~/.ssh/authorized_keys eintragen."
  else
    echo " - Kein Key erzeugt (ausgewählt)."
    echo "Wenn du bereits einen Key hochgeladen hast, stelle sicher:"
    echo "  - ${SSH_DIR}/authorized_keys existiert und gehört ${USER_NAME}:${USER_NAME}"
    echo "  - Rechte: ~/.ssh = 700, authorized_keys = 600"
  fi

  echo
  echo "Teste JETZT bitte den SSH-Login (falls SSH genutzt wird)."
  read -rp "ENTER drücken, sobald du getestet hast (oder STRG+C zum Abbrechen) ... " _

  if yesno "Soll ich sshd_config für Key-only Login anpassen und ssh/sshd neu laden?" "n"; then
    if ! dpkg -s openssh-server >/dev/null 2>&1; then
      echo "openssh-server ist nicht installiert. Installiere..."
      apt-get install -y openssh-server
    fi

    SSHD_CONFIG="/etc/ssh/sshd_config"
    cp -a "${SSHD_CONFIG}" "${SSHD_CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"

    set_sshd_option() {
      local key="$1" value="$2"
      if grep -qE "^[#[:space:]]*${key}[[:space:]]+" "${SSHD_CONFIG}"; then
        sed -i -E "s|^[#[:space:]]*${key}[[:space:]]+.*|${key} ${value}|g" "${SSHD_CONFIG}"
      else
        echo "${key} ${value}" >> "${SSHD_CONFIG}"
      fi
    }

    set_sshd_option "PubkeyAuthentication" "yes"
    set_sshd_option "PasswordAuthentication" "no"
    set_sshd_option "ChallengeResponseAuthentication" "no"

    if command -v systemctl >/dev/null 2>&1; then
      systemctl reload ssh || systemctl reload sshd || systemctl restart ssh || systemctl restart sshd
    else
      service ssh reload || service ssh restart || true
    fi

    echo " - SSH/sshd neu geladen."
  else
    echo "OK, keine automatische SSH-Härtung vorgenommen."
  fi
else
  echo " - Benutzer ${USER_NAME} existiert nicht. SSH-Abschnitt vollständig übersprungen."
fi

echo
echo "[9/9] Optional: Docker (offizielles Docker Repository) installieren?"
if yesno "Soll Docker installiert werden?" "n"; then
  echo " - Entferne ggf. konfliktierende/alte Docker-Pakete (falls vorhanden)..."
  apt-get remove -y docker.io docker-doc docker-compose podman-docker containerd runc 2>/dev/null || true

  echo " - Installiere Voraussetzungen"
  apt-get update -y
  apt-get install -y ca-certificates curl

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc

  . /etc/os-release
  ARCH="$(dpkg --print-architecture)"
  CODENAME="${VERSION_CODENAME:-trixie}"

  cat > /etc/apt/sources.list.d/docker.list <<EOF
deb [arch=${ARCH} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${CODENAME} stable
EOF

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  if getent group docker >/dev/null 2>&1; then
    usermod -aG docker "${USER_NAME}" 2>/dev/null || true
    echo " - ${USER_NAME} zur docker-Gruppe hinzugefügt (wirksam nach neuem Login)."
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl enable --now docker || true
  else
    service docker start || true
  fi

  docker version || true
else
  echo " - Docker Installation übersprungen."
fi

# ---------- Status-Ausgabe ----------
echo
echo "==================== STATUS ===================="
FINAL_HOST="$(hostname 2>/dev/null || true)"
FINAL_FQDN="$(hostname -f 2>/dev/null || true)"

IFACE="$(get_primary_iface)"
IP_CIDR="-"
NETMASK="-"
GATEWAY="$(get_gateway || true)"
DNS_LIST="$(get_dns_list_compact || true)"

if [[ -n "${IFACE}" ]]; then
  IP_CIDR="$(get_ip_cidr "${IFACE}" || true)"
  if [[ -n "${IP_CIDR}" && "${IP_CIDR}" != "-" ]]; then
    NETMASK="$(cidr_to_netmask "${IP_CIDR}")"
  fi
fi

LANGUAGE="$(grep -E '^LANG=' /etc/default/locale 2>/dev/null | head -n1 | cut -d= -f2- || true)"
DISK_TOTAL="$(get_disk_total || true)"
RAM_TOTAL="$(get_ram_total || true)"

echo "Hostname / FQDN : ${FINAL_HOST} / ${FINAL_FQDN}"
echo "Netzwerk        : Interface=${IFACE:-unbekannt}"
echo "IP / Netzmaske  : ${IP_CIDR:--} / ${NETMASK:--}"
echo "Gateway         : ${GATEWAY:--}"
echo "DNS             : ${DNS_LIST:--}"
echo "Sprache/Locale  : ${LANGUAGE:--}"
echo "HDD Gesamt      : ${DISK_TOTAL:--}"
echo "RAM Gesamt      : ${RAM_TOTAL:--}"
echo "Benutzer ugg7   : ${USER_CREATED_STATUS}"
echo "================================================"
echo
echo "Fertig."
